### ISSUE TITLE
Account migration support?

### ISSUE THREAD

**Issue by poVoq** [iNPUTmice/QuicksyServer#1]
This seems like a good base for making account migration possible in XMPP.

Both from the perspective of changing phone numbers as well as having to change JIDs due to a server going permanently offline.

Right now it seems like multiple phone numbers are already on the todo list which would seem like the first step. This could probably be extended to JIDs and maybe supplemented by other identifiers like email.

In addition an easy service to notify users of changed addresses/phone numbers would be probably good. This could maybe be done by allowing users to mark a primary contact and clients could check with quicksy if the primary contact has changed or look up alternative contacts if the primary is unreachable.

A bit OT, but do you know of any such work done as XEPs? Ideally there should also be a OMEMO compatible way to have account aliases.

**Comment by iNPUTmice** [comment]
I disagree that we need a central directory for JID to JID mapping and more importantly I don’t think I should be the one to develop and/or host such a directory.
