### ISSUE TITLE
Idea: Use XEP-0158: CAPTCHA Forms for SMS verification

### ISSUE THREAD

**Issue by pravi** [iNPUTmice/QuicksyServer#7]
While discussing about https://github.com/iNPUTmice/Conversations/issues/4419 it occurred to me that https://xmpp.org/extensions/xep-0158.html could be used to verify sms otp allowing any xmpp client to sign up to Quicksy. It can be hidden behind a configuration option and turned off by default.

Then only the querying directory part will need to implemented in the client for adding Quicksy experience to other platforms. If we generalize this to a contact discovery xep with captcha based authentication/publishing, we may be able to get more clients to adopt it as well.

If the idea is good and only coding is needed, we'd like to crowd fund it as part of prav app project.

**Comment by iNPUTmice** [comment]
Hi @pravi 

please see me response on the Conversations issue tracker on my stanza on your app.
